# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import empty_table_pb2 as empty__table__pb2


class SearchTableStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetData = channel.unary_unary(
        '/SearchTable/GetData',
        request_serializer=empty__table__pb2.Table.SerializeToString,
        response_deserializer=empty__table__pb2.Empty.FromString,
        )


class SearchTableServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetData(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_SearchTableServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetData': grpc.unary_unary_rpc_method_handler(
          servicer.GetData,
          request_deserializer=empty__table__pb2.Table.FromString,
          response_serializer=empty__table__pb2.Empty.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'SearchTable', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
